### ISSUE TITLE
For some coin combinations it doesn't return the minimal solution

### ISSUE THREAD

**Issue by petrjoachim** [IT-Sage/VendingMachineSample#1]
Consider following test case, for available coins 1, 4 and 5 it should return coins three coins `4, 4, 4` not four coins `5, 5, 1, 1`.

```
        [Test]
        public void Test11()
        {
            int[] availableCoins = { 1, 4, 5 };
            var coinService = new CoinService(availableCoins);
            var coins = coinService.GetCoinsBasic(12);

            Assert.That(coins.Count, Is.EqualTo(3));
        }
```

**Comment by IT-Sage** [comment]
Yes, it's due to `GetCoinsBasic()` method, which implements only basic greedy algorithm, which works well only with canonical coin systems. [Wikipedia](https://en.wikipedia.org/wiki/Change-making_problem)

When you use `GetCoins()` method, it works well. I've just tried this code sample locally.
```
[Test]
public void Test11()
{
    int[] availableCoins = { 1, 4, 5 };
    var coinService = new CoinService(availableCoins);
    var coins = coinService.GetCoins(12);

    Assert.That(coins.Count, Is.EqualTo(3));
}

```

**Comment by petrjoachim** [comment]
Works like a charm, I didn't notice that I'm using different algorithm. 🙈

**Comment by IT-Sage** [comment]
Yeah, sorry, it's not obvious, I could emphasize it :)
